# -*- coding: utf-8 -*-
"""Mindsurf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyx6K61NSSMaIsVx-sNgzR4YgEQVP-QU
"""

!pip install sionna

# Environemnt setup (signal channel)
# downlink

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # Suppresses annoying TensorFlow warnings
import tensorflow as tf
import sionna as sn

# --- THE SIONNA 1.0 FIX IS HERE ---
from sionna.phy.channel.tr38901 import AntennaArray, CDL

# --- 1. System Parameters for 150 Mbit/s ---
carrier_frequency = 3.5e9 # 3.5 GHz (n78 mid-band)
subcarrier_spacing = 30e3 # 30 kHz SCS
fft_size = 2048           # FFT size for 50 MHz bandwidth
speed = 3.0               # Mobile UE speed in m/s (Walking/Mindsurfing)

print("Initializing 5G NR Digital Twin...")

# --- 2. Antenna Configuration (2x2 MIMO) ---
# Base Station (gNB) Antenna
bs_array = AntennaArray(
    num_rows=1,
    num_cols=1,
    polarization="dual",
    polarization_type="cross",
    antenna_pattern="38.901",
    carrier_frequency=carrier_frequency
)

# User Equipment (UE) Antenna
ut_array = AntennaArray(
    num_rows=1,
    num_cols=1,
    polarization="dual",
    polarization_type="cross",
    antenna_pattern="38.901",
    carrier_frequency=carrier_frequency
)

# --- 3. The "Mindsurf" Channel: CDL-C (Urban NLoS) ---
cdl_model = CDL(
    model="C",                # CDL-C is the 3GPP standard for Urban NLoS
    delay_spread=300e-9,      # 300 nanoseconds delay (signals bouncing off buildings)
    carrier_frequency=carrier_frequency,
    ut_array=ut_array,
    bs_array=bs_array,
    direction="downlink",     # gNB to UE
    min_speed=speed
)

# --- 4. Generate Channel Realizations ---
# We simulate a batch of 100 independent channel snapshots simultaneously
batch_size = 100
sampling_rate = fft_size * subcarrier_spacing

# 'a' = path gains (how strong the bounces are)
# 'tau' = path delays (when the bounces arrive)
a, tau = cdl_model(batch_size=batch_size, num_time_steps=1, sampling_frequency=sampling_rate)

print(f"✅ Successfully initialized CDL-C Urban NLoS Channel!")
print(f"Multipath Gains Tensor Shape: {a.shape}")
print(f"Multipath Delays Tensor Shape: {tau.shape}")
print("Ready to inject the 150 Mbit/s waveform into the channel.")

# Transmitter of 150mbit/s
# reality is chaos

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sionna as sn
from sionna.phy.mimo import StreamManagement
from sionna.phy.ofdm import ResourceGrid, ResourceGridMapper
from sionna.phy.mapping import Mapper
from sionna.phy.channel import OFDMChannel # <-- The Fix is here

# --- 1. Define the 5G Frame Structure ---
rx_tx_association = np.array([[1]])
num_streams_per_tx = 1
stream_manager = StreamManagement(rx_tx_association, num_streams_per_tx)

resource_grid = ResourceGrid(
    num_ofdm_symbols=14,
    fft_size=fft_size,
    subcarrier_spacing=subcarrier_spacing,
    num_tx=1,
    num_streams_per_tx=1,
    cyclic_prefix_length=144,
    pilot_pattern=None,
    pilot_ofdm_symbol_indices=[]
)

# --- 2. The Modulation Components ---
num_bits_per_symbol = 8
mapper = Mapper(constellation_type="qam", num_bits_per_symbol=num_bits_per_symbol)
rg_mapper = ResourceGridMapper(resource_grid)

# --- 3. Generate the 150 Mbit/s Signal ---
bits_per_slot = resource_grid.num_data_symbols * num_bits_per_symbol

print(f"Generating {bits_per_slot} bits per slot...")
binary_source = tf.random.uniform(shape=[batch_size, 1, 1, bits_per_slot], minval=0, maxval=2, dtype=tf.int32)

qam_symbols = mapper(binary_source)
ofdm_grid = rg_mapper(qam_symbols)

print(f"✅ Transmitter Grid Ready. Shape: {ofdm_grid.shape}")

# --- 4. The "Mindsurf" Test: Push it through the Channel ---
# The OFDMChannel block natively combines the CDL model and the noise
ofdm_channel = OFDMChannel(
    cdl_model,
    resource_grid,
    add_awgn=True,
    normalize_channel=True,
    return_channel=False
)

# We define a Noise Variance (No). 0.01 is a realistic SNR for this test.
no = 0.01
rx_grid_rough = ofdm_channel(ofdm_grid, no)

print("✅ Signal transmitted through Urban NLoS frequency channel.")

# --- 5. Visualization: The "Pitch" Slide ---
plt.figure(figsize=(10, 5))

# Plot 1: What we sent
plt.subplot(1, 2, 1)
# We flatten the tensor so matplotlib can scatter it easily
tx_constellation = tf.reshape(qam_symbols[0,0,0,:], [-1])
plt.scatter(tf.math.real(tx_constellation), tf.math.imag(tx_constellation), c='blue', s=1)
plt.title("Transmitted Signal (The Dream)\nPerfect 256-QAM")
plt.grid(True)
plt.axis('equal')

# Plot 2: What arrived (The Reality)
rx_constellation = tf.reshape(rx_grid_rough[0,0,0,:,:], [-1])

plt.subplot(1, 2, 2)
plt.scatter(tf.math.real(rx_constellation), tf.math.imag(rx_constellation), c='red', s=1)
plt.title("Received Signal (Mindsurf Reality)\nUrban Fading + Noise")
plt.grid(True)
plt.axis('equal')

plt.tight_layout()
plt.show()

# equalizer (pilot) to receie sent signal
# recover 256-QAM structure from the chaos.

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sionna as sn
from sionna.phy.mimo import StreamManagement
from sionna.phy.ofdm import ResourceGrid, ResourceGridMapper, LSChannelEstimator, LMMSEEqualizer
from sionna.phy.mapping import Mapper
from sionna.phy.channel import OFDMChannel

# --- 1. System Setup (Now WITH Pilots!) ---
stream_manager = StreamManagement(np.array([[1]]), 1)

resource_grid = ResourceGrid(
    num_ofdm_symbols=14,
    fft_size=2048,
    subcarrier_spacing=30e3,
    num_tx=1,
    num_streams_per_tx=1,
    cyclic_prefix_length=144,
    pilot_pattern="kronecker",
    pilot_ofdm_symbol_indices=[2, 11]
)

# --- 2. Transmitter (Tx) ---
mapper = Mapper(constellation_type="qam", num_bits_per_symbol=8)
rg_mapper = ResourceGridMapper(resource_grid)

# Generate raw data bits
bits_per_slot = resource_grid.num_data_symbols * 8
binary_source = tf.random.uniform(shape=[100, 1, 1, bits_per_slot], minval=0, maxval=2, dtype=tf.int32)

x_tx = mapper(binary_source)
x_rg_tx = rg_mapper(x_tx)

# --- 3. The Channel (The Chaos) ---
ofdm_channel = OFDMChannel(cdl_model, resource_grid, add_awgn=True, normalize_channel=True, return_channel=False)
no = 0.01
y_rx = ofdm_channel(x_rg_tx, no)

# --- 4. The Receiver (Rx) Brain (THE FIX IS HERE) ---
# Step A: Estimate the channel using the Pilots
estimator = LSChannelEstimator(resource_grid, interpolation_type="nn")
h_hat, err_var = estimator(y_rx, no)  # <-- Fix: y_rx and no are separate arguments

# Step B: Equalize the signal using the LMMSE algorithm
equalizer = LMMSEEqualizer(resource_grid, stream_manager)
x_hat, no_eff = equalizer(y_rx, h_hat, err_var, no)  # <-- Fix: Brackets removed

print("✅ Signal Estimated and Equalized!")

# --- 5. Visualization: The Final Pitch Slide ---
plt.figure(figsize=(15, 5))

# Plot 1: The Dream (Tx)
plt.subplot(1, 3, 1)
tx_constellation = tf.reshape(x_tx[0,0,0,:], [-1])
plt.scatter(tf.math.real(tx_constellation), tf.math.imag(tx_constellation), c='blue', s=1)
plt.title("1. Transmitted Data\n(Perfect 256-QAM)")
plt.axis('equal'); plt.grid(True)

# Plot 2: The Reality (Rx BEFORE Equalizer)
plt.subplot(1, 3, 2)
rx_chaos = tf.reshape(y_rx[0,0,0,:,:], [-1])
plt.scatter(tf.math.real(rx_chaos), tf.math.imag(rx_chaos), c='red', s=1)
plt.title("2. Mindsurf Chaos\n(Urban Fading + Noise)")
plt.axis('equal'); plt.grid(True)

# Plot 3: The Recovery (Rx AFTER Equalizer)
plt.subplot(1, 3, 3)
rx_clean = tf.reshape(x_hat[0,0,0,:], [-1])
plt.scatter(tf.math.real(rx_clean), tf.math.imag(rx_clean), c='green', s=1)
plt.title("3. Equalized Data\n(Recovered Stream)")
plt.axis('equal'); plt.grid(True)

plt.tight_layout()
plt.show()

# bit error rate (BER) showing stable signal
# running equalizer output through demapper
# "How confident are you that this dot represents a 1 or a 0?"
# Because an (Log likelihood rato) LLR > 0 means the bit is likely a 0, and an LLR < 0 means the bit is likely a 1

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sionna as sn
from sionna.phy.channel.tr38901 import AntennaArray, CDL
from sionna.phy.mimo import StreamManagement
from sionna.phy.ofdm import ResourceGrid, ResourceGridMapper, LSChannelEstimator, LMMSEEqualizer
from sionna.phy.mapping import Mapper, Demapper
from sionna.phy.channel import OFDMChannel

# --- 1. System Parameters & Hardware (Ettus X410 Specs) ---
carrier_frequency = 3.5e9
subcarrier_spacing = 30e3
fft_size = 2048
speed = 3.0
batch_size = 1 #100

bs_array = AntennaArray(num_rows=1, num_cols=1, polarization="dual", polarization_type="cross", antenna_pattern="38.901", carrier_frequency=carrier_frequency)
ut_array = AntennaArray(num_rows=1, num_cols=1, polarization="dual", polarization_type="cross", antenna_pattern="38.901", carrier_frequency=carrier_frequency)

cdl_model = CDL(model="C", delay_spread=300e-9, carrier_frequency=carrier_frequency, ut_array=ut_array, bs_array=bs_array, direction="downlink", min_speed=speed)
stream_manager = StreamManagement(np.array([[1]]), 1)

resource_grid = ResourceGrid(
    num_ofdm_symbols=14,
    fft_size=fft_size,
    subcarrier_spacing=subcarrier_spacing,
    num_tx=1,
    num_streams_per_tx=1,
    cyclic_prefix_length=144,
    pilot_pattern="kronecker",
    pilot_ofdm_symbol_indices=[2, 11]
)

# --- 2. Transmitter (Tx) - Generating 150 Mbit/s Data ---
mapper = Mapper(constellation_type="qam", num_bits_per_symbol=8)
rg_mapper = ResourceGridMapper(resource_grid)

bits_per_slot = resource_grid.num_data_symbols * 8
binary_source = tf.random.uniform(shape=[batch_size, 1, 1, bits_per_slot], minval=0, maxval=2, dtype=tf.int32)

x_tx = mapper(binary_source)
x_rg_tx = rg_mapper(x_tx)

# --- 3. The Channel (Mindsurf Chaos) ---
ofdm_channel = OFDMChannel(cdl_model, resource_grid, add_awgn=True, normalize_channel=True, return_channel=False)
no = 0.01
y_rx = ofdm_channel(x_rg_tx, no)

# --- 4. The Receiver (Rx) Brain - Untangling the Signal ---
estimator = LSChannelEstimator(resource_grid, interpolation_type="nn")
h_hat, err_var = estimator(y_rx, no)

equalizer = LMMSEEqualizer(resource_grid, stream_manager)
x_hat, no_eff = equalizer(y_rx, h_hat, err_var, no)

# --- 5. Mathematical Proof (BER Extraction) ---
demapper = Demapper("app", "qam", num_bits_per_symbol=8)
llrs = demapper(x_hat, no_eff)
# THE FIX: Sionna LLR > 0 means the bit is a 1
b_hat = tf.cast(llrs > 0, tf.int32)
b_hat_flat = tf.reshape(b_hat, tf.shape(binary_source))
errors = tf.cast(tf.math.not_equal(binary_source, b_hat_flat), tf.float32)
ber = tf.reduce_mean(errors)

print("=== 5G Digital Twin: Pitch Validation Metrics ===")
print(f"Total Bits Transmitted: {bits_per_slot * batch_size}")
print(f"Uncoded Bit Error Rate (BER): {ber.numpy():.4f}")
if ber.numpy() < 0.05:
    print("✅ STATUS: Highly Stable Link. Ready for LDPC Error Correction.")
else:
    print("⚠️ STATUS: High Error Rate. Consider dropping to 64-QAM.")

# --- 6. Visualization Slide for Aalto ---
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
tx_constellation = tf.reshape(x_tx[0,0,0,:], [-1])
plt.scatter(tf.math.real(tx_constellation), tf.math.imag(tx_constellation), c='blue', s=1)
plt.title("1. Transmitted Data\n(Perfect 256-QAM)")
plt.axis('equal'); plt.grid(True)

plt.subplot(1, 3, 2)
rx_chaos = tf.reshape(y_rx[0,0,0,:,:], [-1])
plt.scatter(tf.math.real(rx_chaos), tf.math.imag(rx_chaos), c='red', s=1)
plt.title("2. Mindsurf Chaos\n(Urban Fading + Noise)")
plt.axis('equal'); plt.grid(True)

plt.subplot(1, 3, 3)
rx_clean = tf.reshape(x_hat[0,0,0,:], [-1])
plt.scatter(tf.math.real(rx_clean), tf.math.imag(rx_clean), c='green', s=1)
plt.title("3. Equalized Data\n(Recovered Stream)")
plt.axis('equal'); plt.grid(True)

plt.tight_layout()
plt.show()

# LDPC (low density parity check) decoder to ensure 0% error rate and 5G digital twin
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sionna as sn

from sionna.phy.channel.tr38901 import AntennaArray, CDL
from sionna.phy.mimo import StreamManagement
from sionna.phy.ofdm import ResourceGrid, ResourceGridMapper, LSChannelEstimator, LMMSEEqualizer
from sionna.phy.mapping import Mapper, Demapper
from sionna.phy.channel import OFDMChannel

# --- NEW: Sionna v1.0+ LDPC Imports ---
from sionna.phy.fec.ldpc.encoding import LDPC5GEncoder
from sionna.phy.fec.ldpc.decoding import LDPC5GDecoder

# --- 1. System Parameters & Hardware (Ettus X410 Specs) ---
carrier_frequency = 3.5e9
subcarrier_spacing = 30e3
fft_size = 2048
speed = 3.0
batch_size = 1

bs_array = AntennaArray(num_rows=1, num_cols=1, polarization="dual", polarization_type="cross", antenna_pattern="38.901", carrier_frequency=carrier_frequency)
ut_array = AntennaArray(num_rows=1, num_cols=1, polarization="dual", polarization_type="cross", antenna_pattern="38.901", carrier_frequency=carrier_frequency)

cdl_model = CDL(model="C", delay_spread=300e-9, carrier_frequency=carrier_frequency, ut_array=ut_array, bs_array=bs_array, direction="downlink", min_speed=speed)
stream_manager = StreamManagement(np.array([[1]]), 1)

resource_grid = ResourceGrid(
    num_ofdm_symbols=14,
    fft_size=fft_size,
    subcarrier_spacing=subcarrier_spacing,
    num_tx=1,
    num_streams_per_tx=1,
    cyclic_prefix_length=144,
    pilot_pattern="kronecker",
    pilot_ofdm_symbol_indices=[2, 11]
)

# --- 2. Transmitter (Tx) WITH LDPC ---
mapper = Mapper(constellation_type="qam", num_bits_per_symbol=8)
rg_mapper = ResourceGridMapper(resource_grid)

# LDPC Setup: We segment the slot into 32 manageable code blocks to save RAM
num_cbs = 32
n_cb = int((resource_grid.num_data_symbols * 8) / num_cbs) # 6144 encoded bits
k_cb = int(n_cb / 2) # 3072 raw data bits (Rate 1/2)

encoder = LDPC5GEncoder(k=k_cb, n=n_cb)
decoder = LDPC5GDecoder(encoder, num_iter=10)

# THE FIX: Generate as int32, but cast to float32 to prevent TensorFlow crashes!
binary_source_int = tf.random.uniform(shape=[batch_size, 1, 1, num_cbs, k_cb], minval=0, maxval=2, dtype=tf.int32)
binary_source = tf.cast(binary_source_int, tf.float32)

# Encode and flatten for the grid
coded_bits = encoder(binary_source)
coded_bits_flat = tf.reshape(coded_bits, [batch_size, 1, 1, -1])

x_tx = mapper(coded_bits_flat)
x_rg_tx = rg_mapper(x_tx)

# --- 3. The Channel (Mindsurf Chaos) ---
ofdm_channel = OFDMChannel(cdl_model, resource_grid, add_awgn=True, normalize_channel=True, return_channel=False)
no = 0.01
y_rx = ofdm_channel(x_rg_tx, no)

# --- 4. The Receiver (Rx) Brain - Untangling the Signal ---
estimator = LSChannelEstimator(resource_grid, interpolation_type="nn")
h_hat, err_var = estimator(y_rx, no)

equalizer = LMMSEEqualizer(resource_grid, stream_manager)
x_hat, no_eff = equalizer(y_rx, h_hat, err_var, no)

# --- 5. Mathematical Proof (BER Extraction with LDPC) ---
demapper = Demapper("app", "qam", num_bits_per_symbol=8)
llrs = demapper(x_hat, no_eff)

# Reshape LLRs back into 32 blocks and decode
llrs_cbs = tf.reshape(llrs, [batch_size, 1, 1, num_cbs, n_cb])
b_hat = decoder(llrs_cbs)

# Compare LDPC recovered bits to the original bits
errors = tf.cast(tf.math.not_equal(binary_source, b_hat), tf.float32)
ber = tf.reduce_mean(errors)

print("=== 5G Digital Twin: Pitch Validation Metrics ===")
print(f"Total Raw Data Bits Transmitted: {k_cb * num_cbs * batch_size}")
print(f"Final Coded Bit Error Rate (BER): {ber.numpy():.6f}")

if ber.numpy() == 0.0:
    print("✅ STATUS: Carrier-Grade Link. Flawless 150 Mbit/s Data Stream Achieved.")
else:
    print("⚠️ STATUS: Residual Errors Detected. Consider dropping to 64-QAM.")

# --- 6. Visualization Slide for Aalto ---
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
tx_constellation = tf.reshape(x_tx[0,0,0,:], [-1])
plt.scatter(tf.math.real(tx_constellation), tf.math.imag(tx_constellation), c='blue', s=1)
plt.title("1. Transmitted Data\n(Perfect 256-QAM)")
plt.axis('equal'); plt.grid(True)

plt.subplot(1, 3, 2)
rx_chaos = tf.reshape(y_rx[0,0,0,:,:], [-1])
plt.scatter(tf.math.real(rx_chaos), tf.math.imag(rx_chaos), c='red', s=1)
plt.title("2. Mindsurf Chaos\n(Urban Fading + Noise)")
plt.axis('equal'); plt.grid(True)

plt.subplot(1, 3, 3)
rx_clean = tf.reshape(x_hat[0,0,0,:], [-1])
plt.scatter(tf.math.real(rx_clean), tf.math.imag(rx_clean), c='green', s=1)
plt.title("3. Equalized Data\n(Recovered Stream before LDPC)")
plt.axis('equal'); plt.grid(True)

plt.tight_layout()
plt.show()

